### ISSUE TITLE
Out of memory on Prometheus VM

### ISSUE THREAD

**Issue by janlunddk** [PacktPublishing/Hands-On-Infrastructure-Monitoring-with-Prometheus#34]
When spinning the VMs up (Chapter 3), the script times out. When visiting the VM in Virtualbox it has an Out of memory error. 

Increasing the memory from 256 to 512 in vagrant_defaults.rb solves this issue.

(Edit: This is on Windows 10)

**Comment by timberkeley** [comment]
Same issue in Ubuntu. Thanks for posting the fix.
