### ISSUE TITLE
Error running 'vagrant up' for Hands-On-Infrastructure-Monitoring-with-Prometheus

### ISSUE THREAD

**Issue by sb1975** [PacktPublishing/Hands-On-Infrastructure-Monitoring-with-Prometheus#37]
Error with vagrant up

==> prometheus: Running provisioner: shell...
    prometheus: Running: C:/Users/esudbat/AppData/Local/Temp/vagrant-shell20201214-17024-1xbwb5v.sh
    prometheus: /vagrant/utils/helpers.sh: line 2: $'\r': command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by kintoandar** [comment]
Hi @sb1975 ,

Full disclosure, the software was properly tested on the [Operating Systems Requirements list](https://github.com/PacktPublishing/Hands-On-Infrastructure-Monitoring-with-Prometheus#software-and-hardware-list) which doesn't include Windows-based systems. With that said, there are [Windows users successfully using this repo](https://github.com/PacktPublishing/Hands-On-Infrastructure-Monitoring-with-Prometheus/issues/34).

The error you're experiencing usually boils down to files created/edited on Windows having different line ending than files created on Linux. This makes me wonder if, for some reason, the file in question was opened/edited in windows. Can you please clone the repo again and try `vagrant up` without opening any of its files on Windows?

Thank you 🙏

**Comment by sarvesh-packt** [comment]
Hi @sb1975 ,

Please reopen if the issue still persists.

Thanks,
