### ISSUE TITLE
Error with completing "vagrant up" in Chapter 3

### ISSUE THREAD

**Issue by bgchance** [PacktPublishing/Hands-On-Infrastructure-Monitoring-with-Prometheus#39]
Without getting vagrant to complete successfully, the book is not useful. Can anyone help with this error? Spending more time trying to figure out vagrant than learning Prometheus. :-(

Vagrant = Vagrant 2.2.17
VirtualBox = 6.1.24
Running on Windows 10 

==> prometheus: Attempting graceful shutdown of VM...
==> prometheus: Booting VM...
==> prometheus: Waiting for machine to boot. This may take a few minutes...
==> prometheus: Machine booted and ready!
==> prometheus: Checking for guest additions in VM...
==> prometheus: Setting hostname...
==> prometheus: Configuring and enabling network interfaces...
==> prometheus: Mounting shared folders...
    prometheus: /vagrant => C:/Users/bgcha/git_repos/Hands-On-Infrastructure-Monitoring-with-Prometheus
==> prometheus: Running provisioner: shell...
    prometheus: Running: C:/Users/bgcha/AppData/Local/Temp/vagrant-shell20210721-12700-eb6oyd.sh
==> prometheus: Running provisioner: shell...
    prometheus: Running: C:/Users/bgcha/AppData/Local/Temp/vagrant-shell20210721-12700-oukj9g.sh
    prometheus: /vagrant/utils/helpers.sh: line 2: $'\r': command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by kintoandar** [comment]
Hi @bgchance

First of all, thank you for trying out these test labs.

The issue you're reporting is very similar to [this one](https://github.com/PacktPublishing/Hands-On-Infrastructure-Monitoring-with-Prometheus/issues/37#issuecomment-744318372), care to try out the proposed solution and validate if it fixes your problem?

**Comment by bgchance** [comment]
Thank you for the quick response. I will review the other thread and find a way to use a non-windows OS to attempt to deploy the environment.

**Comment by bgchance** [comment]
Thank you. I was able to get this up and running on Windows. I changed the git checkout config to checkout-as-is.

**Comment by kintoandar** [comment]
@bgchance super happy to hear that! 

Thank you for buying the book and using the test labs 🙏
